---
- name: Check if Block object type is defined
  fail:
    msg: "Missidng required param: block_url_type"
  when: block_url_type is not defined
  delegate_to: localhost

- name: Block URL Object Mandatory Params - block_name, block_url
  fail:
    msg: "Missing any one of mandatory required parameters: block_name, block_url"
  when:
    - block_url_type == "url"
    - block_name is not defined or block_url is not defined
  delegate_to: localhost

- name: Block Network Feed Mandatory Params - block_name
  fail:
    msg: "Missing mandatory required parameters: block_name"
  when:
    - block_url_type == "feed"
    - block_name is not defined
  delegate_to: localhost

- name: Creating URL object
  ftd_configuration:
    operation: upsertURLObject
    data:
      version: "{{ block_version | default(omit) }}"
      name: "{{ block_name }}"
      description: "{{ block_url_description | default(omit) }}"
      url: "{{ block_url }}"
      id: "{{ block_id | default(omit) }}"
      type: "{{ block_url_object | default('urlobject') }}"
    register_as: url_object
  when: block_url_type == "url"

- name: Getting URL Feed
  ftd_configuration:
    operation: getURLFeedCategoryList
    filters:
      name: "{{ block_name }}"
    register_as: url_object
  when: block_url_type == "feed"

- name: Find Security Intelligence URL Policy
  ftd_configuration:
    operation: getSecurityIntelligenceURLPolicyList
    register_as: policies
  when: url_object is defined

- name: Setup SecurityIntelligenceURLPolicy via URL Object
  ftd_configuration:
    operation: editSecurityIntelligenceURLPolicy
    data:
      id: "{{ policies[0]['id'] }}"
      name: "{{ policies[0]['name'] }}"
      version: "{{ policies[0]['version'] }}"
      blockForBlacklist: "{{ policies[0]['blockForBlacklist'] + [url_object] }}"
      whitelist: "{{ policies[0]['whitelist'] }}"
      type: securityintelligenceurlpolicy
    path_params:
      objId: "{{ policies[0]['id'] }}"
  register: setup_status_url
  when: block_url_type == "url"

- name: Setup SecurityIntelligenceURLPolicy via URL Feed
  ftd_configuration:
    operation: editSecurityIntelligenceURLPolicy
    data:
      id: "{{ policies[0]['id'] }}"
      name: "{{ policies[0]['name'] }}"
      version: "{{ policies[0]['version'] }}"
      blockForBlacklist: "{{ policies[0]['blockForBlacklist'] + [url_object[0]] }}"
      whitelist: "{{ policies[0]['whitelist'] }}"
      type: securityintelligenceurlpolicy
    path_params:
      objId: "{{ policies[0]['id'] }}"
  register: setup_status_feed
  when: block_url_type == "feed"

- name: Start deployment
  ftd_configuration:
    operation: addDeployment
    register_as: deployment_job
  when: setup_status_url.changed or setup_status_feed.changed

- name: Poll deployment status until the job is finished
  ftd_configuration:
    operation: getDeployment
    path_params:
      objId: '{{ deployment_job.id }}'
    register_as: deployment_status
  until: deployment_status.endTime != -1
  retries: 100
  delay: 3
  when: setup_status_url.changed or setup_status_feed.changed

- name: Stop the playbook if the deployment failed
  fail:
    msg: 'Deployment failed. Status: {{ deployment_status.statusMessages }}'
  when:
    - setup_status_url.changed or setup_status_feed.changed
    - deployment_status.state != 'DEPLOYED'
