---
- name: Check if Block object type is defined
  fail:
    msg: "Missidng required param: block_network_type"
  when: block_network_type is not defined
  delegate_to: localhost

- name: Block Network Object Mandatory Params - block_name, block_value, block_subtype
  fail:
    msg: "Missing any one of mandatory required parameters: block_name, block_value, block_subtype"
  when:
    - block_network_type == "network"
    - block_name is not defined or block_value is not defined or block_subtype is not defined
  delegate_to: localhost

- name: Block Network Feed Mandatory Params - block_name
  fail:
    msg: "Missing mandatory required parameters: block_name"
  when:
    - block_network_type == "feed"
    - block_name is not defined
  delegate_to: localhost

- name: Creating Network object
  ftd_configuration:
    operation: upsertNetworkObject
    data:
      version: "{{ block_version | default(omit) }}"
      name: "{{ block_name }}"
      description: "{{ block_description | default(omit) }}"
      subType: "{{ block_subtype }}"
      value: "{{ block_value }}"
      isSystemDefined: "{{ block_system_defined | default(omit) }}"
      dnsResolution: "{{ block_dns_resolution | default(omit) }}"
      id: "{{ block_id | default(omit) }}"
      type: "{{ block_type | default('networkobject') }}"
    register_as: network_object
  when: block_network_type == "network"

- name: Getting Network Feed
  ftd_configuration:
    operation: getNetworkFeedCategoryList
    filters:
      name: "{{ block_name }}"
    register_as: network_object
  when: block_network_type == "feed"

- name: Find Security Intelligence Network Policy
  ftd_configuration:
    operation: getSecurityIntelligenceNetworkPolicyList
    register_as: policies
  when: network_object is defined

- name: Setup SecurityIntelligenceNetworkPolicy via Network Object
  ftd_configuration:
    operation: editSecurityIntelligenceNetworkPolicy
    data:
      version: "{{ policies[0]['version'] }}"
      name: "{{ policies[0]['name'] }}"
      blockForBlacklist: "{{ policies[0]['blockForBlacklist'] + [network_object] }}"
      whitelist: "{{ policies[0]['whitelist'] }}"
      id: "{{ policies[0]['id'] }}"
      type: securityintelligencenetworkpolicy
    path_params:
      objId: "{{ policies[0]['id'] }}"
  register: setup_status_network
  when: block_network_type == "network"

- name: Setup SecurityIntelligenceNetworkPolicy via Network Feed
  ftd_configuration:
    operation: editSecurityIntelligenceNetworkPolicy
    data:
      version: "{{ policies[0]['version'] }}"
      name: "{{ policies[0]['name'] }}"
      blockForBlacklist: "{{ policies[0]['blockForBlacklist'] + [network_object[0]] }}"
      whitelist: "{{ policies[0]['whitelist'] }}"
      id: "{{ policies[0]['id'] }}"
      type: securityintelligencenetworkpolicy
    path_params:
      objId: "{{ policies[0]['id'] }}"
  register: setup_status_feed
  when: block_network_type == "feed"

- name: Start deployment
  ftd_configuration:
    operation: addDeployment
    register_as: deployment_job
  when: setup_status_network.changed or setup_status_feed.changed

- name: Poll deployment status until the job is finished
  ftd_configuration:
    operation: getDeployment
    path_params:
      objId: '{{ deployment_job.id }}'
    register_as: deployment_status
  until: deployment_status.endTime != -1
  retries: 100
  delay: 3
  when: setup_status_network.changed or setup_status_feed.changed

- name: Stop the playbook if the deployment failed
  fail:
    msg: 'Deployment failed. Status: {{ deployment_status.statusMessages }}'
  when:
    - setup_status_network.changed or setup_status_feed.changed
    - deployment_status.state != 'DEPLOYED'
