---
- name: Check if Unblock object type is defined
  fail:
    msg: "Missidng required param: unblock_network_type"
  when: unblock_network_type is not defined
  delegate_to: localhost

- name: Unblock Network Object Mandatory Params - unblock_name, unblock_value, unblock_subtype
  fail:
    msg: "Missing any one of mandatory required parameters: unblock_name, unblock_value, unblock_subtype."
  when:
    - unblock_network_type == "network"
    - unblock_name is not defined or unblock_value is not defined or unblock_subtype is not defined
  delegate_to: localhost

- name: Unblock Network Feed Mandatory Params - unblock_name
  fail:
    msg: "Missing mandatory required parameters: unblock_name"
  when:
    - unblock_network_type == "feed"
    - unblock_name is not defined
  delegate_to: localhost

- name: Creating Network object
  ftd_configuration:
    operation: upsertNetworkObject
    data:
      version: "{{ unblock_version | default(omit) }}"
      name: "{{ unblock_name }}"
      description: "{{ unblock_description | default(omit) }}"
      subType: "{{ unblock_subtype }}"
      value: "{{ unblock_value }}"
      isSystemDefined: "{{ unblock_system_defined | default(omit) }}"
      dnsResolution: "{{ unblock_dns_resolution | default(omit) }}"
      id: "{{ unblock_id | default(omit) }}"
      type: "{{ unblock_type | default('networkobject') }}"
    register_as: network_object
  when: unblock_network_type == "network"

- name: Getting Network Feed
  ftd_configuration:
    operation: getNetworkFeedCategoryList
    filters:
      name: "{{ unblock_name }}"
    register_as: network_object
  when: unblock_network_type == "feed"

- name: Find Security Intelligence Network Policy
  ftd_configuration:
    operation: getSecurityIntelligenceNetworkPolicyList
    register_as: policies
  when: unblock_network_type is defined

- name: Setup SecurityIntelligenceNetworkPolicy via Network Object
  ftd_configuration:
    operation: editSecurityIntelligenceNetworkPolicy
    data:
      version: "{{ policies[0]['version'] }}"
      name: "{{ policies[0]['name'] }}"
      blacklistForBlock: "{{ policies[0]['blacklistForBlock'] }}"
      unblock: "{{ policies[0]['unblock'] + [network_object] }}"
      id: "{{ policies[0]['id'] }}"
      type: securityintelligencenetworkpolicy
    path_params:
      objId: "{{ policies[0]['id'] }}"
  register: setup_status_network
  when: unblock_network_type == "network"

- name: Setup SecurityIntelligenceNetworkPolicy via Network Feed
  ftd_configuration:
    operation: editSecurityIntelligenceNetworkPolicy
    data:
      version: "{{ policies[0]['version'] }}"
      name: "{{ policies[0]['name'] }}"
      blacklistForBlock: "{{ policies[0]['blacklistForBlock'] }}"
      unblock: "{{ policies[0]['unblock'] + [network_object[0]] }}"
      id: "{{ policies[0]['id'] }}"
      type: securityintelligencenetworkpolicy
    path_params:
      objId: "{{ policies[0]['id'] }}"
  register: setup_status_feed
  when: unblock_network_type == "feed"

- name: Start deployment
  ftd_configuration:
    operation: addDeployment
    register_as: deployment_job
  when: setup_status_network.changed or setup_status_feed.changed

- name: Poll deployment status until the job is finished
  ftd_configuration:
    operation: getDeployment
    path_params:
      objId: '{{ deployment_job.id }}'
    register_as: deployment_status
  until: deployment_status.endTime != -1
  retries: 100
  delay: 3
  when: setup_status_network.changed or setup_status_feed.changed

- name: Stop the playbook if the deployment failed
  fail:
    msg: 'Deployment failed. Status: {{ deployment_status.statusMessages }}'
  when:
    - setup_status_network.changed or setup_status_feed.changed
    - deployment_status.state != 'DEPLOYED'
